name: 522-group-24
channels:
  - conda-forge
dependencies:
  - altair-all=5.4.0
  - ipykernel=6.29.5
  - matplotlib=3.9.2
  - nb_conda_kernels=2.5.1
  - pandera=0.20.2
  - pandas=2.2.2
  - python=3.11
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - vega_datasets=0.9.0
  - vegafusion=1.6.9
  - pip=24.3.1
  - requests=2.31.0
  - click=8.1.7
  - quarto=1.5.57
  - make=4.4.1
  - pytest=8.3.4
  - responses=0.24.1
     